UN-OCHA/gho-site

config/core.entity_form_display.paragraph.bottom_figure_row.default.yml
config/core.entity_view_display.paragraph.bottom_figure_row.default.yml
config/field.field.paragraph.bottom_figure_row.field_dataset.yml
config/field.storage.paragraph.field_bottom_figures.yml
config/field.storage.paragraph.field_dataset.yml
html/themes/custom/common_design_subtheme/components/gho-bottom-figure-row/gho-bottom-figure-row.css
html/themes/custom/common_design_subtheme/templates/fields/field--paragraph--field-dataset--bottom-figure-row.html.twig

I spent an ungodly amount of time trying to format the link but I failed so here's a PR with the text hyperlinked.
RTL layout also included in the PR now. You have to create an Arabic translation of the page to see the effect, because otherwise the `<article>` for the Article content type will itself have `dir="ltr"` as an attribute, which applies both sets in a rather strange way. I'm not sure if we can/should safeguard against that situation. It seems they'll have translations for everything.

GHO-11: add the source link

---

config/core.entity_form_display.node.article.default.yml
config/core.entity_form_display.taxonomy_term.appeals.default.yml
config/core.entity_view_display.node.article.default.yml
config/core.entity_view_display.node.article.teaser.yml
config/core.entity_view_display.taxonomy_term.appeals.default.yml
config/field.field.node.article.field_appeals.yml
config/field.field.taxonomy_term.appeals.field_appeal_extended.yml
config/field.storage.node.field_appeals.yml
config/field.storage.taxonomy_term.field_appeal_extended.yml
config/language.content_settings.taxonomy_term.appeals.yml
config/taxonomy.vocabulary.appeals.yml
html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml
html/themes/custom/common_design_subtheme/components/gho-appeals-tags/README.md
html/themes/custom/common_design_subtheme/components/gho-appeals-tags/gho-appeals-tags.css
html/themes/custom/common_design_subtheme/templates/fields/field--field-appeals.html.twig
html/themes/custom/common_design_subtheme/templates/taxonomy/taxonomy-term--appeals.html.twig

PR contains config/theming for Appeals tags. They're attached to Article nodes but I think the template names I chose to overrode mean it will work anywhere (as paragraph, on different content types, etc)
The colors are stored in the component-specific CSS and they came straight off of hum-insight.info production. 
```sh
$ drush cim
$ drush cr
```
After importing config, create taxonomy terms with the following titles: HRP, FA, RRP, Other — they should automatically pick up the appropriate colors and appear like so:
I used similar styles to some of the other flex components (negative margin on container) to ensure that RTL works out of the box. The tags themselves are English only and not translatable. I used the [Arabic-language 2020 GHO …

GHO-12: Appeals tags

---

composer.json
composer.lock
config/core.entity_form_display.node.article.default.yml
config/core.entity_form_display.taxonomy_term.appeals.default.yml
config/core.entity_view_display.node.article.default.yml
config/core.entity_view_display.node.article.related_article.yml
config/core.extension.yml
html/modules/custom/gho_fields/README.md
html/modules/custom/gho_fields/config/schema/gho_fields.schema.yml
html/modules/custom/gho_fields/gho_fields.link_attributes.yml
html/modules/custom/gho_fields/gho_fields.module
html/modules/custom/gho_fields/src/Plugin/Field/FieldFormatter/GhoFurtherReadingLinkFormatter.php
html/modules/custom/gho_fields/src/Plugin/Field/FieldWidget/GhoFurtherReadingLinkWidget.php
html/modules/custom/gho_fields/templates/gho-further-reading-link-formatter.html.twig
html/themes/custom/common_design_subtheme/components/gho-further-reading/gho-further-reading.css
html/themes/custom/common_design_subtheme/templates/fields/field--field-further-reading.html.twig

Ticket: GHO-13
This PR is a complement for https://github.com/UN-OCHA/gho-site/pull/37.
It adds a custom widget and formatter (and template) for the further reading links similar to what was done for the `Dataset` links.
Initially it was going to extend what `link_attributes` does but after looking at the code, it appeared we don't need the module and a simple custom widget would do the trick to add the `source` field. So this PR also removes the `link_attributes` module.
**Form widget**
Note: there is no placeholder for the source. If we think one should be added, then this can be done by adding a `#placeholder` in the `GhoFurtherReadingLinkWidget.php` file.
**Formatter**
**Styling/template**
I think that the `›` for the chevron should be replaced by a SVG icon in the markup …

[GHO-13] Further reading part 2 - custom widget/formatter

---

config/responsive_image.styles.related_article_thumbnail.yml
html/themes/custom/common_design_subtheme/components/gho-related-article/gho-related-article.css
html/themes/custom/common_design_subtheme/templates/fields/field--node--field-related-articles--article.html.twig
html/themes/custom/common_design_subtheme/templates/nodes/node--article--related-article.html.twig

Small follow-ups from work in #33 
- the max-width has been removed from the component, which simplified some responsive image styles config.
- I restored the title which is evident in the PDF where the component is seen in context. We originally built using the screenshot very early in the PDF which had no title.

GHO-14: Related Article followups

---

html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml

Load the `gho-bleed` library very eagerly since it's used by any Article.

[GHO-51] gho-bleed should be loaded by all Article/Sub-Article nodes

---

html/themes/custom/common_design_subtheme/components/gho-bottom-figure-row/gho-bottom-figure-row.css

Ticket: GHO-11
According to the PDF, there is no padding left (or right on RTL) for the bottom figures:
PDF:
PR:

[GHO-11] Fix bottom figures left/right padding

---

html/themes/custom/common_design_admin_subtheme/css/styles.css

No ticket, but while auditing the image aspect ratios I noticed these styles got dropped when we set the three-col view mode to  be default.

Restore admin styles for Facts and Figures paragraph type

---

html/themes/custom/common_design_subtheme/components/gho-photo-gallery/gho-photo-gallery.css

Follow-ups for #59 
- IE11 photo grallery layout fixed. [Details if you want them](https://stackoverflow.com/a/52669657).
- Location/Caption had space re-introduced, I presume when we shuffled the markup around and stopped using `display:inline` on caption directly.

[GHO-16] photo gallery pt3

---

config/core.entity_form_display.media.video.media_library.yml
config/field.field.node.story.field_media.yml

Small improvements to the work in #61 to surface the credit field, and also mark the Image/Video as required when creating a Story entity. The config screen I finally found:
And the new upload form with required Credits field:

GHO-33: multimedia credit field

---

composer.patches.json
config/social_auth_hid.settings.yml
config/user.role.administrator.yml

This should maybe eventually go into social_auth_hid with a setting to turn it off or on.

[OPS-6971] Allow HID logins during maintenance mode, so we can test and populate prod with content.

---

config/core.entity_form_display.node.article.home_page.yml
config/core.entity_form_mode.node.home_page.yml
config/user.role.administrator.yml
html/modules/custom/gho_access/README.md
html/modules/custom/gho_access/gho_access.module
html/modules/custom/gho_access/gho_access.permissions.yml
html/modules/custom/gho_access/gho_access.services.yml
html/modules/custom/gho_access/src/Access/GhoLanguageVisibilityAccessCheck.php
html/modules/custom/gho_access/src/Routing/RouteSubscriber.php
html/modules/custom/gho_general/gho_general.module

Ticket: GHO-25
**Background**: 
1. Drupal's default behavior is to display content in their default language when the translation is missing. So we end up, for example, with articles in Arabic with sub-articles in English because not yet translated.
2. It's been requested to be able to only show the homepage in Arabic for example while content in that language is being added to the site.
**Solution**
So this modules deals with dark magic to add access checks to allow the visibility of content in a given language (after a million of hours battling Drupal):
1. It defines a "view untranslated content" permission (given to admins) to allow to see content in any language regardless of the status of the translations. Said otherwise, if you have this permission, then you get the default Drupal's …

[GHO-25] Language visibility

---

config/core.entity_form_display.paragraph.interactive_content.default.yml
config/core.entity_view_display.paragraph.interactive_content.default.yml
config/core.extension.yml
config/field.field.paragraph.interactive_content.field_dataset.yml
config/field.field.paragraph.interactive_content.field_image.yml
config/field.field.paragraph.interactive_content.field_link.yml
config/field.field.paragraph.interactive_content.field_title.yml
config/field.field.paragraph.interactive_content.field_type.yml
config/field.storage.paragraph.field_link.yml
config/field.storage.paragraph.field_type.yml
config/image.style.full_width_100.yml
config/image.style.full_width_133.yml
config/image.style.full_width_180.yml
config/image.style.full_width_200.yml
config/image.style.full_width_33.yml
config/image.style.full_width_50.yml
config/image.style.full_width_66.yml
config/image.style.full_width_90.yml
config/language.content_settings.taxonomy_term.interactive_content_type.yml
config/paragraphs.paragraphs_type.interactive_content.yml
config/responsive_image.styles.interactive_content.yml
config/taxonomy.vocabulary.interactive_content_type.yml
html/modules/custom/gho_general/gho_general.links.action.yml
html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml
html/themes/custom/common_design_subtheme/components/gho-interactive-content/README.md
html/themes/custom/common_design_subtheme/components/gho-interactive-content/gho-interactive-content.css
html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--interactive-content.html.twig

Tickets: GHO-19, GHO-21
This adds a paragraph type for interactive content with a type (pre-title), title, image (screenshot of the interactive content), link (to the interactive content) and dataset source.
This quite similar to the "Stories" except it's a paragraph type not a content type because we don't need to have individually accessible pages for those as they embed/link to external content.
There is new "interactive content type" vocabulary to avoid mixing the terms with the story types.
This uses the `linked_responsive_image_media_formatter` custom module to generate the clickable image.
The  styling re-uses the story  type one with a large image (904px).
`drush cim`, `drush cr` and add some interactive content type terms and then a interactive content paragraph to an article.

[GHO-19] Interactive content

---

config/core.entity_form_display.node.article.default.yml
config/core.entity_form_display.node.article.home_page.yml
config/core.entity_view_display.node.article.default.yml
config/core.entity_view_display.node.article.home_page.yml
config/core.entity_view_display.node.article.related_article.yml
config/core.entity_view_display.node.article.sub_article.yml
config/core.entity_view_display.node.article.teaser.yml
config/field.field.node.article.field_caption.yml
config/field.storage.node.field_caption.yml
html/modules/custom/gho_fields/config/schema/gho_fields.schema.yml
html/modules/custom/gho_fields/gho_fields.module
html/modules/custom/gho_fields/src/Plugin/Field/FieldFormatter/GhoCaptionFormatter.php
html/modules/custom/gho_fields/templates/gho-caption-formatter.html.twig
html/themes/custom/common_design_subtheme/common_design_subtheme.theme
html/themes/custom/common_design_subtheme/components/gho-article/gho-article.css
html/themes/custom/common_design_subtheme/templates/fields/field--node--field-caption--article.html.twig

Ticket: GHO-9, GHO-34
This adds the article caption via a double field on the node and using the credits from the hero image.
**Note** The margin between the title and the caption need to be adjusted as well as lots of other places so leaving that for another PR.
`drush cim`, `drush cr` and add a location/caption to an article.
Note: there may be a classic issue of the chicken and egg like it happened in other PRs, when running the drush commands. Another run of those 2 commands should fix it.

[GHO-34] Article caption

---

html/modules/custom/gho_access/gho_access.module
html/modules/custom/gho_access/src/Access/GhoLanguageVisibilityAccessCheck.php
html/modules/custom/gho_access/src/GhoAccessServiceProvider.php
html/modules/custom/gho_access/src/Menu/GhoMenuLinkTreeManipulators.php
html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml
html/themes/custom/common_design_subtheme/common_design_subtheme.theme
html/themes/custom/common_design_subtheme/components/gho-page-404/README.md
html/themes/custom/common_design_subtheme/components/gho-page-404/gho-page-404.css
html/themes/custom/common_design_subtheme/templates/menu--page-not-found.html.twig

Ticket: GHO-96
This customizes a bit the 404 page with links to the homepage and main articles. This based on the ReliefWeb 404: https://reliefweb.int/blabla
This PR contains also some modifications to the access checks to handle menus.
If the homepage in the requested language doesn't exist, it shows a link to the English page:
1. `The page @path was not found.`
2. `Sorry for any inconvenience.`
3. `Here are some useful pages to help you get back on track:`
4. `Home page in @language`
`drush cim` and `drush cr` and just visit a page that doesn't exist. Ex: https://gho.test/blabla and https://gho.test/fr/blabla

[GHO-96] Page 404

---

config/editor.editor.limited_html.yml
config/filter.format.limited_html.yml
html/themes/custom/common_design_subtheme/common_design_subtheme.info.yml
html/themes/custom/common_design_subtheme/components/gho-text/gho-text.css
html/themes/custom/common_design_subtheme/css/ckeditor/styles.css

Ticket: GHO-98
Add a "highlight" for paragraph (`<p>`) in ckeditor for `text` paragraph types to allow the following:
`drush cim`, `drush cr`, edit a `text` paragraph, select a paragraph, click "styles" dropdown and select "Highlight".

[GHO-98] Add highlight style for paragraphs in ckeditor

---

html/themes/custom/common_design_admin_subtheme/css/styles.css
html/themes/custom/common_design_subtheme/components/gho-text/gho-text.css

I made some assumptions in #94  and #98 which need to be reversed. Here's how it works now:
(the highlight can be selected but is intentionally NOT honored)
(highlight also NOT reflected on public theme)

GHO-98: undo css mods

---

config/image.style.full_width_2_1_100.yml
config/image.style.full_width_2_1_105.yml
config/image.style.full_width_2_1_123.yml
config/image.style.full_width_2_1_133.yml
config/image.style.full_width_2_1_180.yml
config/image.style.full_width_2_1_200.yml
config/image.style.full_width_2_1_210.yml
config/image.style.full_width_2_1_246.yml
config/image.style.full_width_2_1_50.yml
config/image.style.full_width_2_1_66.yml
config/image.style.full_width_2_1_90.yml
config/responsive_image.styles.hero_image.yml

Ticket: GHO-64
This simply adjusts the ratio of the hero images to `2:1`, adding corresponding image styles.
Note: this doesn't apply to the hero image of the homepage.

[GHO-64] Adjust ratio of hero image for articles

---

html/themes/custom/common_design_admin_subtheme/css/styles.css
html/themes/custom/common_design_subtheme/components/gho-text/gho-text.css
html/themes/custom/common_design_subtheme/css/ckeditor/styles.css

Ticket: GHO-103
This enables the caption styling for blockquotes inside text paragraphs.
Not sure about the margins because there is no example of pull quotes in any of the documents.

[GHO-103] Enable caption styling for blockquotes inside text paragraphs

---

html/themes/custom/common_design_subtheme/components/gho-footnotes/gho-footnotes.css
html/themes/custom/common_design_subtheme/components/gho-further-reading/gho-further-reading.css

Ticket: GHO-59, GHO-61
This adjusts the styling of the references and fixes an issue with the "further reading" title as they are supposed to have the same appearance.
This also adjusts the margins/translation etc. for the footnotes popup to stay attached to the left and right and work with the `904px` of the content area.
Note:  the backlinks `super` vertical align changes the spacing impression between the footnotes. I'll create a ticket for the backlinks because I think they want to change their design according to the prototype v4. Fine as it is for now.

[GHO-59][GHO-61] Adjust footnotes

---

html/themes/custom/common_design_subtheme/components/gho-separator/gho-separator.css

Ticket: GHO-105
This adjusts the separator to be full width or half width of the `reading width` (720px). I'm wondering if that's correct or if we want to be relative to the `content width` (904px).

[GHO-105] Adjust the separators to be full or half of the width of the reading width

---

config/core.entity_form_display.node.article.default.yml
config/core.entity_form_display.node.article.home_page.yml
config/core.entity_form_display.node.story.default.yml
config/core.entity_form_display.paragraph.image_with_text.default.yml
config/core.entity_form_display.paragraph.section_index.default.yml
config/field.field.paragraph.further_reading.field_links.yml
html/modules/custom/gho_fields/src/Plugin/Field/FieldFormatter/GhoFurtherReadingLinkFormatter.php
html/modules/custom/gho_fields/src/Plugin/Field/FieldWidget/GhoFurtherReadingLinkWidget.php

Ticket: GHO-94
This PR does 2 things:
1. It hides all the "about text formats" below formatted text fields because it's useless as we don't allow text format selection
2. It fixes an issue with the source field validation for further reading links, fixes the display of the link title when none is provided just to be thorough as this cannot happen because of the third change: only allow external links and make link title mandatory.
Note: regarding the last point (external link and title), those were the original settings before moving the further reading links to a paragraph type where I overlooked the original settings:
`drush cim`, `drush cr` and edit a story and check that there is no "about text format" below the `footnotes` and `source` fields and add a further reading paragraph and …

[GHO-94] Bug fixes following permission review

---

config/core.entity_view_display.node.article.default.yml
config/core.entity_view_display.node.article.home_page.yml
config/paragraphs.paragraphs_type.layout.yml
html/themes/custom/common_design_subtheme/layouts/twocol_section/twocol_section.css

Ticket: GHO-101
This brings some simple changes to allow the use of the 2 columns layout. That doesn't change anything for the existing content but in case it is decided to go with the 2 columns option then it's "ready".
I also removed the other layouts (3, 4 columns, grid) to avoid giving "ideas".
`drush cim`, `drush cr`

[GHO-101] Allow 2 columns layout and limit width

---

html/themes/custom/common_design_subtheme/components/gho-author/gho-author.css

Ticket: GHO-62
This depends on #119 being merged.
This adds a border bottom to the author component to look like:

[GHO-62] Add bottom border to author component

---

html/themes/custom/common_design_subtheme/templates/fields/field--paragraph--field-paragraphs--facts-and-figures.html.twig

Small fixup to get our styles (which were correct to begin with) applying cleanly within the `.content-width` container class.

[GHO-111] ensure negative margins are enforced separately from content-width

---

html/themes/custom/common_design_subtheme/templates/nodes/node--article--home-page.html.twig

Ticket: GHO-128
This simply adds some `if` to only show the tag line and download button when the corresponding fields in the homepage form are filled in. This way if they change their mind, then we don't have to do anything (🤞).

[GHO-128] Hide tagline and download button on hero

---

html/themes/custom/common_design_subtheme/components/gho-text/gho-text.css

Ticket: GHO-121
Another short PR. 
**Note**: This results in having blockquotes with the highlight style applied to look like other paragraphs with this style, so let's wait for confirmation before merging.

[GHO-121] Always use dark grey for highlight style

---

html/modules/custom/gho_fields/src/Plugin/Field/FieldFormatter/GhoDatawrapperFormatter.php

Ticket: GHO-126
Minor change to restore the ID prefix for the datawrapper iframes. That doesn't have any impact but it's cleaner.

[GHO-126] Fix datawrapper iframe ID

---

html/modules/custom/gho_fields/src/Plugin/Field/FieldFormatter/GhoNumberFormatter.php

Ticket: GHO-154
- Number > 1,000,000 => precision 1 (ex: 12.3 million, 8.7 billion)
- Number > 10,000 and < 1,000,000 => precision 2, use "million" (ex: 0.54 million, 0.02 million)
- Number > 1,000 and < 10,000 => formatted with thousand separator (depends on language): (ex: 2,345)
- Number < 1,000 => raw number (ex: 678)

[GHO-154] Adjust number formatting for Needs and Requirements

---

config/field.field.taxonomy_term.needs_and_requirements.field_people_in_need.yml
config/field.field.taxonomy_term.needs_and_requirements.field_people_targeted.yml
config/field.field.taxonomy_term.needs_and_requirements.field_requirements.yml
config/views.view.needs_and_requirements.yml
html/modules/custom/gho_fields/src/Plugin/Field/FieldFormatter/GhoNumberFormatter.php
html/modules/custom/gho_figures/src/Form/GhoFiguresImportNeedsAndRequirementsFiguresForm.php

Ticket: GHO-158
This handles TBC values for Needs and Requirements. In the backend the values are stored as `0`.
`0` is displayed as `TBC` in the backend and importer overview to ease understanding and is displayed as `-` in NaR paragraphs so that translation is not needed (confirmed with Edgar).
Summary: `-1, 0, - or TBC` in spreadsheet -> stored as `0` -> displayed as `-`
`drush cr`, `drush cim`, then import a spreadsheet (there is one attached to the ticket where Total as 2 TBC values), check the preview, then check the homepage after import it should show `-`.

[GHO-158] Handle Needs and Requirements TBC values

---

config/core.entity_form_display.paragraph.article_list.default.yml
config/core.entity_form_display.paragraph.section_index.default.yml
config/core.entity_view_display.paragraph.article_list.default.yml
config/core.entity_view_display.paragraph.section_index.default.yml
config/field.field.paragraph.article_list.field_links.yml
config/field.field.paragraph.article_list.field_title.yml
config/field.field.paragraph.section_index.field_caption.yml
config/field.field.paragraph.section_index.field_image.yml
config/field.field.paragraph.section_index.field_paragraphs.yml
config/field.storage.paragraph.field_caption.yml
config/paragraphs.paragraphs_type.article_list.yml
html/modules/custom/gho_fields/config/schema/gho_fields.schema.yml
html/modules/custom/gho_fields/gho_fields.module
html/modules/custom/gho_fields/src/Plugin/Field/FieldFormatter/GhoArticleListFormatter.php
html/modules/custom/gho_fields/templates/gho-article-list-formatter.html.twig
html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml
html/themes/custom/common_design_subtheme/common_design_subtheme.theme
html/themes/custom/common_design_subtheme/components/gho-article-list/README.md
html/themes/custom/common_design_subtheme/components/gho-article-list/gho-article-list.css
html/themes/custom/common_design_subtheme/components/gho-section-index/gho-section-index.css
html/themes/custom/common_design_subtheme/templates/fields/field--paragraph--field-caption--section-index.html.twig
html/themes/custom/common_design_subtheme/templates/fields/field--paragraph--field-image--section-index.html.twig
html/themes/custom/common_design_subtheme/templates/fields/field--paragraph--field-links--article-list.html.twig
html/themes/custom/common_design_subtheme/templates/nodes/node--article--home-page.html.twig
html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--article-list.html.twig
html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--section-index.html.twig

Ticket: GHO-167
This adds an "article list" paragraph type for the links in a section index with an optional title and a list of internal links. There is a new formatter to be able to get the node titles for the links.
Section index paragraph types are modified with an image field, a caption (location + text) like articles and can now only have "article list" paragraphs.
Styling is changed to match what is in the new PDF.
**Note**: the margins are too big in my opinion on smaller screens but no values were provided so....
`Drush cim`, `drush cr` (possible a few times) then edit the homepage, and fill the section index paragraphs.

[GHO-167] Homepage v3

---

html/modules/custom/gho_fields/src/Plugin/Field/FieldFormatter/GhoRelatedArticlesFormatter.php
html/themes/custom/common_design_subtheme/common_design_subtheme.theme

Ticket: GHO-151
This replaces the logic to get the related articles to get the next accessible article in the order of the main navigation. So for example, for the last article of the "Introduction and Foreword" menu, the link will be the first article of the "Trends and challenges" menu etc.
There is no change to the styling.
`Next article`
`drush cr` and check **as an anonymous user** that navigation via the "next article" is the same as the main navigation.

[GHO-151] Display next article instead of more from this section

---

html/themes/custom/common_design_subtheme/templates/cd/cd-header/cd-ocha.html.twig

I hotfixed `main` to get a few small things on prod without deploying homepage work. This PR will cleanup the conflicts between `develop` and `main` — then the normal PRs from `develop` to `main` will start working again.

Resolve hotfix-2020-11-30

---

html/modules/custom/gho_general/src/GhoGeneralServiceProvider.php
html/modules/custom/gho_general/src/OEmbed/GhoResourceFetcher.php

Ticket: GHO-170
It happens that the issue with the youtube videos is due to the youtube oembed proxy that doesn't always return the correct content-type header: `application/json` and sometimes wrongly `text/html` while the response body is a json string with the embed data.
So this overrides the media oembed resource fetcher service to deal with that quirk.
`drush cr`.
@rupl This cannot be really tested aside of making sure the videos still appear, so you'll have to trust me on this and just check I didn't typo-ed anything in the code ;-)

[GHO-170] Override the media oembed resource fetcher to handle youtube quirks

---

config/views.view.content.yml
config/views.view.content_taxonomy_terms.yml
config/views.view.media.yml
config/views.view.media_translations.yml
config/views.view.needs_and_requirements.yml
config/views.view.paragraphs.yml
config/views.view.translations.yml
html/modules/custom/gho_general/gho_general.links.action.yml

Tickets: GHO-74, GHO-86, GHO-87, GHO-88
This improves the views used for the `/admin/content/` pages:
- Add translation overview for media and add `videos` and `authors` pages
- Add `destination` parameter to go back to the overview after editing or creating a node, term or media
- Remove links to term pages because they don't make sense for the GHO site
- Link the Needs and requirements to their edit page
`drush cim`, `drush cr`, go to the different `/admin/content` pages, check they all show an overview (NaR is a bit different with the actual figures) and click on some `edit` and `create` links

[GHO-86-87-88] Improve admin content views

---

composer.json
composer.lock

Recommended by @lazysoundsystem for my PHP woes after updating composer (output by Drupal as best I can tell)
```
Fatal Error: composer.lock was created for PHP version 7.4 or higher but the current PHP version is 7.3.18.
```

Set PHP to 7.3 in composer.json

---

config/core.entity_form_display.node.article.default.yml
config/core.entity_form_display.node.article.home_page.yml
config/core.entity_view_display.node.article.default.yml
config/core.entity_view_display.node.article.home_page.yml
config/core.entity_view_display.node.article.preview.yml
config/core.entity_view_display.node.article.related_article.yml
config/core.entity_view_display.node.article.sub_article.yml
config/core.entity_view_display.node.article.teaser.yml
config/core.extension.yml
config/field.field.node.article.field_pdf.yml
config/field.storage.node.field_pdf.yml
config/user.role.anonymous.yml
config/user.role.authenticated.yml
html/modules/custom/gho_download/README.md
html/modules/custom/gho_download/gho_download.info.yml
html/modules/custom/gho_download/gho_download.permissions.yml
html/modules/custom/gho_download/gho_download.routing.yml
html/modules/custom/gho_download/src/Controller/GhoDownloadController.php

Ticket: GHO-29
This is the first part of GHO-29 to create upload PDFs to articles and have a download URL. Next PR will integrate that with the work on GHO-7.
This provides a route to have permanent download URLs for the PDF version of an article: https://gho.unocha.org/node/NODEID/download.
Drupal being what it is, the original filename is not saved... so unfortunately the filename when saving the above url may have the `_X` suffix. [0]
It's also not possible to have drupal rename the file to preserve its URL. [1]
- [0] https://www.drupal.org/project/drupal/issues/3032376
- [1] https://www.drupal.org/project/drupal/issues/2648816
This is inspired from https://www.drupal.org/project/media_entity_download
`drush cim`, `drush cr` then add a file to an article and access it via …

[GHO-29] Article PDF download

---

html/themes/custom/common_design_subtheme/templates/fields/field--taxonomy-term--needs-and-requirements.html.twig

This branch was supposed to have the PO files in it, but after doing all the data entry and exporting them, the diff was way bigger than I expected and my local DB seems to have lost a whole lot of translations for other things. I briefly reviewed them and they _seem_ to be admin-facing but it was a huge list and I didn't want to review individual strings.
I will re-do the data entry on prod for the strings that exist and in the mean time let's get this Needs and Requirements string translated for the deploy.

[GHO-186] translate Needs and Requirements label

---

config/user.role.administrator.yml

Ticket: GHO-189
This adds the missing permission to allow editors (Admins) to select a paragraph's behavior. It's only useful for the "bottom figures" to select their appearance (like Top figures or like bottom figures).

[GHO-189] Add permission for editors to select paragraph behavior

---

html/themes/custom/common_design_subtheme/templates/block/block--gho-main-menu.html.twig
html/themes/custom/common_design_subtheme/templates/navigation/menu--main.html.twig

Ticket: GHO-190
This makes the templates for the GHO main menu compatible with the latest version of the common design theme.
The changes in the `menu--main.html.twig` should be ported to the common design theme.

[GHO-190] Update main menu templates to be compatible with latest version of CD base theme

---

composer.lock
composer.patches.json
patches/README.md
patches/module--layout-paragraphs--display-proper-language-in-preview.patch

Ticket: GHO-194
This applies a patch to the layout_paragraphs module to display paragraph previews in the proper language based on the translation target and source languages.

[GHO-194] Fix language of paragraph preview

---

config/common_design_subtheme.settings.yml

Ticket: CD-270
This saves the node title settings for the subtheme as the base theme settings are not inherited.
Enables the special handling of the node title for the `home_page` and `full` view modes.

[CD-270] Save subtheme settings for node title

---

html/themes/custom/common_design_subtheme/templates/block/block--system-branding-block.html.twig

Template update to allow site name to be translated, which is used as alt text in our site logo. The logo itself already renders in each supported language.
⚠️ Seeing the translated text may depend on entering content on the "Interface Translation" config screen: https://gho.test/admin/config/regional/translate
Look for the alt text on a non-english page of the website, such as https://gho.test/fr

GHO-197: translatable alt text for Site Logo
