html/themes/custom/common_design_subtheme/components/gho-aside/README.md, html/themes/custom/common_design_subtheme/components/gho-aside/gho-aside.css, html/themes/custom/common_design_subtheme/templates/fields/field--paragraph--field-title--facts-and-figures.html.twig, html/themes/custom/common_design_subtheme/templates/nodes/node--field-story--teaser.html.twig
The new method we settled on for pre-title, per ticket discussion. I think we only had two of these, so the refactor was pretty minor.
=> GHO-39: add pre-title using a method from W3 recommendations

config/core.entity_form_display.node.article.default.yml, config/core.entity_view_display.media.image.related_article_thumb.yml, config/core.entity_view_display.node.article.default.yml, config/core.entity_view_display.node.article.related_article.yml, config/core.entity_view_mode.media.related_article_thumb.yml, config/core.entity_view_mode.node.related_article.yml, config/field.field.node.article.field_related_articles.yml, config/field.storage.node.field_related_articles.yml, config/image.style.1104_x_678.yml, config/image.style.296_x_182.yml, config/image.style.368_x_226.yml, config/image.style.592_x_364.yml, config/image.style.736_x_452.yml, config/responsive_image.styles.related_article_thumbnail.yml, html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml, html/themes/custom/common_design_subtheme/components/gho-related-article/README.md, html/themes/custom/common_design_subtheme/components/gho-related-article/gho-related-article.css, html/themes/custom/common_design_subtheme/templates/fields/field--node--field-related-articles--article.html.twig, html/themes/custom/common_design_subtheme/templates/nodes/node--article--related-article.html.twig
Allows an editor to add entity references that appear as Related Articles. I chose a standard field as it felt most sensible, and the examples in the PDF always appear at the end of the Article.
Excuse the use of weird floats. It would be grand to use CSS Grid but IE doesn't support it well. Combined with the fact that the title is first in source order, I had to get a little creative. Better than untwisting how to move things around in twig, haha.
```
$ drush cim
$ drush cr # for new theme library
```
After it's set up you have to add some Article references to an Article. I tried to be thorough; testing in LTR and RTL on Chrome, FF, and IE11. Mobile tested in Chrome devtools and real iOS Safari.
I attached a screencast of the the responsive image styles in action **to the ticket**, and …
=> GHO-14: Related Articles

html/themes/custom/common_design_subtheme/components/gho-sub-article/gho-sub-article.css
Ticket: GHO-47
Everything is in the PR's title. Some screenshot:
=> [GHO-47] Fix vertical alignement of appeal tags and spacing when wraping

html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml, html/themes/custom/common_design_subtheme/components/gho-story/README.md, html/themes/custom/common_design_subtheme/components/gho-story/gho-story.css, html/themes/custom/common_design_subtheme/components/gho-text/README.md, html/themes/custom/common_design_subtheme/components/gho-text/gho-text.css, html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--story.html.twig, html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--text.html.twig
Now that we have sub-articles in place, I re-did the work from #41 to fit within the current content/theme setup.
Testing is just `drush cr` for the libraries
=> GHO-50: reading width pt2

composer.json, docker/Dockerfile, docker/redis.services.yml
Redis configuration is all handled via Ansible.
=> [OPS-6891] Add redis, so we can use ElastiCache for speed improvements.

config/responsive_image.styles.story.yml
Ticket: GHO-17
Fix wrong image style used for "tablet x2" in the Story responsive image style.
=> [GHO-17] Fix Story responsive image style

html/themes/custom/common_design_subtheme/templates/paragraphs/paragraph--interactive-content.html.twig
Ticket: GHO-97
As simple as what the title says.
=> [GHO-97] Remove black background for interactive content

config/core.base_field_override.menu_link_content.menu_link_content.changed.yml, config/core.base_field_override.menu_link_content.menu_link_content.description.yml, config/language.content_settings.menu_link_content.menu_link_content.yml, config/user.role.administrator.yml
Ticket: GHO-99, GHO-85
Allow editors to modify menus  via structure > menus and enable menu translations.
`drush cim`, `drush cr`, log in as normal admin user, go to "structure > menus", click on edit menu for "main menu", check you can re-order, rename and translate sub-menus.
=> [GHO-99] Menus

html/themes/custom/common_design_admin_subtheme/css/styles.css
Get admin styles working for highlights.
=> [GHO-98] admin style for highlight

config/field.field.node.story.field_media.yml, config/field.field.node.story.field_type.yml
Ticket: GHO-102
Remove the requirements on the story type and media for stories as some of them don't have an image ("text box").
=> [GHO-102] Remove requirements of type and media for stories

html/themes/custom/common_design_subtheme/components/gho-bottom-figure-row/gho-bottom-figure-row.css, html/themes/custom/common_design_subtheme/components/gho-footnotes/gho-footnotes.css, html/themes/custom/common_design_subtheme/components/gho-further-reading/gho-further-reading.css, html/themes/custom/common_design_subtheme/components/gho-needs-and-requirements/gho-needs-and-requirements.css, html/themes/custom/common_design_subtheme/components/gho-related-articles/gho-related-articles.css, html/themes/custom/common_design_subtheme/components/gho-section-index/gho-section-index.css, html/themes/custom/common_design_subtheme/components/gho-separator/gho-separator.css, html/themes/custom/common_design_subtheme/components/gho-story/gho-story.css, html/themes/custom/common_design_subtheme/components/gho-sub-article/gho-sub-article.css
Ticket: GHO-114
This replaces the `#ccc` used for border with the requested `#d8d8d8`.
=> [GHO-114] Replace border color

html/themes/custom/common_design_subtheme/components/gho-aside/gho-aside.css, html/themes/custom/common_design_subtheme/components/gho-further-reading/gho-further-reading.css, html/themes/custom/common_design_subtheme/components/gho-interactive-content/gho-interactive-content.css, html/themes/custom/common_design_subtheme/components/gho-related-articles/gho-related-articles.css, html/themes/custom/common_design_subtheme/components/gho-section-index/gho-section-index.css
Ticket: GHO-59
This depends on #119 being merged.
A few vertical margin fixes after doing another review pass.
=> [GHO-59] Fix some vertical margins

html/themes/custom/common_design_subtheme/templates/taxonomy/taxonomy-term--appeals.html.twig
Drupal trying to be a little too careful here..
=> [GHO-160] get 3RP appeals tag to be correct color

html/themes/custom/common_design_subtheme/templates/cd/cd-header/cd-ocha.html.twig
Updating OCHA Services. Merging without review FYI @orakili
=> [GHO-169] add Hum-Insight to OCHA Services

html/modules/custom/gho_fields/src/Plugin/Field/FieldFormatter/GhoRelatedArticlesFormatter.php, html/themes/custom/common_design_subtheme/common_design_subtheme.theme, html/themes/custom/common_design_subtheme/templates/cd/cd-header/cd-ocha.html.twig, html/themes/custom/common_design_subtheme/templates/nodes/node--article--sub-article.html.twig
Two small changes to slip onto prod before the big day! Merging without review FYI @orakili.
See #173 and #170 and #172
=> Hotfix 2020-11-30

html/modules/custom/gho_fields/src/Plugin/Field/FieldFormatter/GhoRelatedArticlesFormatter.php, html/themes/custom/common_design_subtheme/common_design_subtheme.theme
This reverts commit 338fc83554882b320dad6775e59fca3f5e5d79fa.
We got WSODs on prod after deploying and ELK seems to be pointing to this function
See [Flowdock](https://www.flowdock.com/app/unocha/global-humanitarian-overview/threads/97zBpGT6t1Bj12lUtELfmmhw1Yc) for logs and stuff
=> Revert the "Next Article" commit

html/modules/custom/gho_fields/gho_fields.module, html/themes/custom/common_design_subtheme/common_design_subtheme.theme
Ticket: GHO-134
Follow-up of #192
=> [GHO-134] Add lazy loading attributes to images

html/themes/custom/common_design_subtheme/common_design_subtheme.theme, html/themes/custom/common_design_subtheme/templates/content/gho-social-links.html.twig
Ticket: GHO-29
See PR's title.
=> [GHO-29] Display download icon when there is a PDF version of an article

README.md, html/modules/custom/gho_access/README.md, html/modules/custom/gho_fields/README.md, html/modules/custom/gho_figures/README.md, html/modules/custom/gho_footnotes/README.md, html/modules/custom/gho_general/README.md, html/themes/custom/common_design_subtheme/README.md, html/themes/custom/common_design_subtheme/components/gho-achievement/README.md, html/themes/custom/common_design_subtheme/components/gho-article-list/README.md, html/themes/custom/common_design_subtheme/components/gho-article/README.md, html/themes/custom/common_design_subtheme/components/gho-author/README.md, html/themes/custom/common_design_subtheme/components/gho-bottom-figure-row/README.md, html/themes/custom/common_design_subtheme/components/gho-caption/README.md, html/themes/custom/common_design_subtheme/components/gho-embed/README.md, html/themes/custom/common_design_subtheme/components/gho-facts-and-figures/README.md, html/themes/custom/common_design_subtheme/components/gho-footnotes/README.md, html/themes/custom/common_design_subtheme/components/gho-further-reading/README.md, html/themes/custom/common_design_subtheme/components/gho-hero-image/README.md, html/themes/custom/common_design_subtheme/components/gho-home-page/README.md, html/themes/custom/common_design_subtheme/components/gho-needs-and-requirements/README.md, html/themes/custom/common_design_subtheme/components/gho-page-404/README.md, html/themes/custom/common_design_subtheme/components/gho-related-articles/README.md, html/themes/custom/common_design_subtheme/components/gho-section-index/README.md, html/themes/custom/common_design_subtheme/components/gho-separator/README.md, html/themes/custom/common_design_subtheme/components/gho-social-links/README.md, html/themes/custom/common_design_subtheme/components/gho-story/README.md, html/themes/custom/common_design_subtheme/components/gho-text/README.md
Ticket: GHO-187
This updates the various README files of the site with hopefully comprehensive and useful information.
=> [GHO-187] Update README files

composer.lock
Ticket: OPS-7230
Bump drupal core and other modules.
=> [OPS-7230] Update drupal core to 8.9.13

config/user.role.administrator.yml, html/themes/custom/common_design_subtheme/templates/block/block--gho-main-menu.html.twig, html/themes/custom/common_design_subtheme/templates/navigation/menu--main.html.twig
- [GHO-190] Fix the main navigation
[GHO-190]: https://humanitarian.atlassian.net/browse/GHO-190
=> Production - 2021/02/03 - Menu fix

html/themes/custom/common_design_subtheme/components/gho-page-node/gho-page-node.css
Ticket: GHO-191
Fix the padding on the homepage.
=> [GHO-191] Fix padding on homepage to have full bleed

.travis.yml, README.md, composer.lock
https://humanitarian.atlassian.net/browse/OPS-7442
and updates ubuntu travis version to 'bionic'.
=> [OPS-7442] update core to 8.9.14

composer.lock
https://humanitarian.atlassian.net/browse/OPS-7493
=> [OPS-7493] security release

composer.json, composer.lock
https://humanitarian.atlassian.net/browse/OPS-7544
=> [OPS-7544] ctools update

composer.lock, symfony.lock
https://humanitarian.atlassian.net/browse/OPS-7688
=> [OPS-7688] update core to 8.9.18

composer.lock
https://humanitarian.atlassian.net/browse/OPS-7780
=> [OPS-7634] update core to 9.2.6
